apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-api.fullname" . }}-db
type: Opaque
data:
  db-host: {{ default "" .Values.secret.db.host | b64enc | quote }}
  db-user: {{ default "" .Values.secret.db.user | b64enc | quote }}
  db-password: {{ default "" .Values.secret.db.password | b64enc | quote }}
  db-database: {{ default "" .Values.secret.db.database | b64enc | quote }}
  db-port: {{ default "" .Values.secret.db.port | b64enc | quote }}
  db-engine: {{ default "" .Values.secret.db.engine | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-api.fullname" . }}-aws
type: Opaque
data:
  aws-region: {{ default "" .Values.secret.aws.region | b64enc | quote }}
  aws-access-key: {{ default "" .Values.secret.aws.access-key | b64enc | quote }}
  aws-secret-key: {{ default "" .Values.secret.aws.secret-key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-api.fullname" . }}-octet
type: Opaque
data:
  octet-api-token: {{ default "" .Values.secret.octet.api-token | b64enc | quote }}
  octet-base-url: {{ default "" .Values.secret.octet.base-url | b64enc | quote }}
  wallet-idx: {{ default "" .Values.secret.octet.wallet-idx | b64enc | quote }}
  recovery-pin: {{ default "" .Values.secret.octet.recovery-pin | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-api.fullname" . }}-alchemy
type: Opaque
data:
  alchemy-api-key: {{ default "" .Values.secret.alchemy.api-key | b64enc | quote }}
  alchemy-host: {{ default "" .Values.secret.alchemy.host | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-api.fullname" . }}-jwt
type: Opaque
data:
  jwt-secret: {{ default "" .Values.secret.alchemy.secret | b64enc | quote }}
  jwt-auth-secret: {{ default "" .Values.secret.alchemy.auth-secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-api.fullname" . }}-encoding
type: Opaque
data:
  hash-ids-key: {{ default "" .Values.secret.encoding.hash-ids-key | b64enc | quote }}
  rsa-private-key: {{ default "" .Values.secret.encoding.rsa-private-key | b64enc | quote }}
  rsa-public-key: {{ default "" .Values.secret.encoding.rsa-public-key | b64enc | quote }}
