apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-aws
data:
  new-account-report-queue-url: {{ default "" .Values.config.newAccountReportQueueUrl | quote }}
  wallet-create-notification-queue-name: {{ default "" .Values.config.walletCreateNotificationQueueName | quote }}
  wallet-create-notification-queue-url: {{ default "" .Values.config.walletCreateNotificationQueueUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-common
data:
  nonce-template: {{ default "" .Values.config.nonceTemplate | b64enc | quote }}
  tos-url: {{ default "" .Values.config.tosUrl | quote }}
  tos-updated: {{ default "" .Values.config.tosUpdated | quote }}
  wallet-backend-base-url: {{ default "" .Values.config.walletBackendBaseUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-identity
data:
  identity-danal-api-base: {{ default "" .Values.config.identityDanalApiBase | quote }}
  identity-danal-target-url: {{ default "" .Values.config.identityDanalTargetUrl | quote }}
  identity-user-danal-target-url: {{ default "" .Values.config.identityUserDanalTargetUrl | quote }}
  identity-reset-pin-danal-target-url: {{ default "" .Values.config.identityResetPinDanalTargetUrl | quote }}
  identity-oauth-client-id: {{ default "" .Values.config.identityOauthClientId | quote }}
  identity-valid-redirect-urls: {{ default "" .Values.config.identityValidRedirectUrls | quote }}
  identity-home-page: {{ default "" .Values.config.identityHomePage | quote }}

