apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-database
type: Opaque
data:
  host: {{ default "" .Values.secret.database.host | b64enc | quote }}
  user: {{ default "" .Values.secret.database.user | b64enc | quote }}
  port: {{ default "" .Values.secret.database.port | b64enc | quote }}
  password: {{ default "" .Values.secret.database.password | b64enc | quote }}
  database: {{ default "" .Values.secret.database.database | b64enc | quote }}
  engine: {{ default "" .Values.secret.database.engine | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-aws
type: Opaque
data:
  aws-region: {{ default "" .Values.secret.awsRegion | quote }}
  aws-access-key: {{ default "" .Values.secret.awsAccessKey | quote }}
  aws-secret-key: {{ default "" .Values.secret.awsSecretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-oauth
data:
  oauth2-token-expires-in-password: {{ default "" .Values.secret.oauth2TokenExpiresInPassword | quote }}
  oauth2-refresh-token-expires-in: {{ default "" .Values.secret.oauth2RefreshTokenExpiresIn | quote }}
  secret-key: {{ default "" .Values.secret.secretKey | quote }}
  reset-pin-jwt-exp: {{ default "" .Values.secret.resetPinJwtExp | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-identity
data:
  identity-danal-cpid: {{ default "" .Values.secret.identityDanalCPID | quote }}
  identity-danal-cppwd: {{ default "" .Values.secret.identityDanalCPPWD | quote }}
  identity-encrypt-key: {{ default "" .Values.secret.identityEncryptKey | quote }}
  identity-valid-redirect-urls: {{ default "" .Values.secret.identityValidRedirectUrls | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-social
data:
  social-login-apple-app-id: {{ default "" .Values.secret.socialLoginAppleAppId | quote }}


