# Default values for wallet-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 293315485843.dkr.ecr.ap-northeast-2.amazonaws.com/kkr/wallet-api:0.0.3-96bbd7f-0
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  common:
    chain-id: ""
  aws:
    wallet-create-notification-queue-name: ""
    wallet-create-notification-queue-url: ""
  jwt:
    expires-in: "3"
secret:
  db:
    host: ""
    user: ""
    password: ""
    database: ""
    port: ""
    engine: ""
  aws:
    region: ""
    access-key: ""
    secret-key: ""
  octet:
    api-token: ""
    base-url: ""
    wallet-id: ""
    recovery-pin: ""
  jwt:
    secret: ""
    auth-secret: ""
  encoding:
    hash-ids-key: ""
    rsa-private-key: ""
    rsa-public-key: ""



podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
